version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_pass
      POSTGRES_DB: erp_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: erp_user
      DB_PASS: erp_pass
      DB_NAME: erp_db
      INIT_ADMIN_PASSWORD: admin
      JWT_SECRET: dev-secret
    depends_on:
      - db
    ports:
      - "3000:3000"    

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8000:8000"

  reverseproxy:
    build: ./reverseproxy
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"

volumes:
  db_data:
